[package]
name = "ptekspy/signal"
description = "Signal"
version = "1.0.0"
license = "Apache-2.0"
authors = ["ptekspy"]
repository = "https://github.com/ptekspy/Signal"
homepage = "https://github.com/ptekspy/Signal"
keywords = ["Signal", "Roblox"]
files = ["src"]
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
